language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
script:
- mvn clean package docker:build
