version: '2'
services:
  eurekaserver:
   image:   bilalwahla/df-eurekasvr:product-selection
   ports:
       - "8761:8761"
  configserver:
    image: bilalwahla/df-confsvr:product-selection
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: bilalwahla/df-zuulsvr:product-selection
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
  database:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=product_selection_local
  customer-location-service:
    image: bilalwahla/df-customer-location-service:product-selection
    ports:
      - "8081:8081"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  catalogue-service:
    image: bilalwahla/df-catalogue-service:product-selection
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  # Attention:  Replace the value in the “command” attribute with the value supplied to you from Papertrail (a free log aggregation app)
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs6.papertrailapp.com:16878
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
